TITLE = 0
ARTIST = 1
ALBUM = 2
YEAR = 3
TRACK = 4
PLAYER_STATUS = 5
TRACK_NUMBER = 6
PLAYLIST_COUNT = 7
VOLUME = 8
REPEAT_STATUS = 9
NETWORK_STATUS = 10
CLIENT_ID = 12
MEMORY_USAGE = 13
NFC_WRITE_STATE = 14
NFC_ENCODING_ALBUM_ID = 15
LAST_NFC_SCAN = 16
TIMESTAMP = 17
WS_CONNECTED = 18
COVER_URL = 19
MUTED = 20

# Keys no display renders — AppState deltas containing only these skip
# display repaints entirely (MQTT still receives them via its own subscriber)
NON_VISUAL_KEYS = {
    MEMORY_USAGE,
    CLIENT_ID,
    WS_CONNECTED,
    NFC_WRITE_STATE,
    NFC_ENCODING_ALBUM_ID,
    LAST_NFC_SCAN,
}